#!/usr/bin/env python3
"""Generates src/web/themes.css: one palette per theme on a fixed OKLCH hue wheel.

Each action kind gets its own hue (neighbours alternate lightness); each theme only sets lightness,
chroma and its neutrals. Every pair of kinds must stay at least MIN_DISTANCE apart in OKLab, so two
categories never end up the same color again. Run: python3 scripts/themes.py
"""
import itertools
import math
import pathlib
import sys

MIN_DISTANCE = 0.075

# kind: (OKLCH hue, lightness offset). Read/search/web share a family on purpose, as do mcp shades.
PLAN = {
    "fail": (25, 0.00), "setup": (48, -0.09), "write": (75, 0.03), "build": (105, 0.10),
    "run": (138, -0.04), "test": (172, 0.10), "docker": (228, -0.07), "read": (260, 0.00),
    "search": (245, 0.08), "web": (280, 0.06), "git": (305, -0.04), "mcp": (340, 0.04),
}
FAMILIES = [{"read", "search", "web"}]

# name: label, base lightness/chroma, neutrals.
THEMES = {
    "tokyo": dict(label="Tokyo Night", L=0.76, C=0.14, bg="#0f1115", panel="#161920", panel2="#1c2029", line="#2a2f3a", fg="#c0caf5", dim="#737aa2", faint="#565f89"),
    "catppuccin": dict(label="Catppuccin Mocha", L=0.80, C=0.11, bg="#11111b", panel="#1e1e2e", panel2="#282839", line="#313244", fg="#cdd6f4", dim="#7f849c", faint="#585b70"),
    "starship": dict(label="Starship", L=0.74, C=0.18, bg="#0b0b0b", panel="#121212", panel2="#1c1c1c", line="#2b2b2b", fg="#e4e4e4", dim="#8a8a8a", faint="#5f5f5f"),
    "dracula": dict(label="Dracula", L=0.80, C=0.17, bg="#21222c", panel="#282a36", panel2="#313442", line="#44475a", fg="#f8f8f2", dim="#a4a9c4", faint="#6272a4"),
    "gruvbox": dict(label="Gruvbox Dark", L=0.72, C=0.13, hue_shift=5, bg="#1d2021", panel="#282828", panel2="#32302f", line="#3c3836", fg="#ebdbb2", dim="#a89984", faint="#7c6f64"),
    "github-light": dict(label="GitHub Light", L=0.52, C=0.15, light=True, bg="#f6f8fa", panel="#ffffff", panel2="#f3f4f6", line="#d0d7de", fg="#1f2328", dim="#59636e", faint="#8c959f"),
}


def oklch_to_hex(L, C, h):
    def conv(c):
        a, b = c * math.cos(math.radians(h)), c * math.sin(math.radians(h))
        l_ = L + 0.3963377774 * a + 0.2158037573 * b
        m_ = L - 0.1055613458 * a - 0.0638541728 * b
        s_ = L - 0.0894841775 * a - 1.2914855480 * b
        l, m, s = l_**3, m_**3, s_**3
        return (4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
                -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
                -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s)
    while C > 0 and not all(-0.001 <= x <= 1.001 for x in conv(C)):
        C -= 0.005  # reduce chroma until inside sRGB
    enc = lambda x: 12.92 * x if x <= 0.0031308 else 1.055 * x ** (1 / 2.4) - 0.055
    return "#" + "".join(f"{round(enc(max(0, min(1, x))) * 255):02x}" for x in conv(max(C, 0)))


def oklab(hexc):
    lin = lambda c: c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = [lin(int(hexc[i:i + 2], 16) / 255) for i in (1, 3, 5)]
    l, m, s = [x ** (1 / 3) for x in (
        0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b,
        0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b,
        0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b)]
    return (0.2104542553 * l + 0.7936177850 * m - 0.0040720468 * s,
            1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s,
            0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s)


def palette(t):
    sign = -1 if t.get("light") else 1  # on light themes "lighter" means darker
    p = {k: oklch_to_hex(t["L"] + sign * dl, t["C"], (h + t.get("hue_shift", 0)) % 360) for k, (h, dl) in PLAN.items()}
    p["agent"] = "#000000" if t.get("light") else "#ffffff"
    return p


def main():
    css = ["/* Generated by scripts/themes.py. Do not edit; change the script and re-run it. */"]
    failed = False
    for i, (name, t) in enumerate(THEMES.items()):
        p = palette(t)
        kinds = list(p)
        close = [(round(math.dist(oklab(p[a]), oklab(p[b])), 3), a, b)
                 for a, b in itertools.combinations(kinds, 2)
                 if not any({a, b} <= f for f in FAMILIES)
                 and math.dist(oklab(p[a]), oklab(p[b])) < MIN_DISTANCE]
        if close:
            failed = True
            print(f"{name}: too close {sorted(close)}", file=sys.stderr)
        neutrals = {k: t[k] for k in ("bg", "panel", "panel2", "line", "fg", "dim", "faint")}
        selector = f':root, :root[data-theme="{name}"]' if i == 0 else f':root[data-theme="{name}"]'
        decls = "\n".join(f"  --{k}: {v};" for k, v in {**neutrals, **p}.items())
        css.append(f"{selector} {{\n  color-scheme: {'light' if t.get('light') else 'dark'};\n{decls}\n}}")
    if failed:
        sys.exit(1)
    out = pathlib.Path(__file__).resolve().parent.parent / "src/web/themes.css"
    out.write_text("\n\n".join(css) + "\n")
    print(f"wrote {out} ({len(THEMES)} themes)")


if __name__ == "__main__":
    main()
